### ISSUE TITLE
Help!  I need a logo!

### ISSUE THREAD

**Issue by larrydiamond** [larrydiamond/sqgraph#1]
I actually have no vision on what I want for a logo exactly.   
It should somehow suggest to people "Graphing" and "Code Health" and not infringe on SonarSource's Intellectual Property.
Proposals are very much welcome with my thanks in advance!

**Comment by the-amazing-atharva** [comment]
Hey !!
I am a beginner designer here and new to GitHub and I tried to make a logo.

Should I send the link or upload a PNG here or how should I send the logo?

**Comment by larrydiamond** [comment]
Hi there!   Welcome!   Please upload the PNG into the issue and I'll take a look.
According to Github, we can attach files right into this form - https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files
Thank you very much for taking a look and creating a logo!

**Comment by the-amazing-atharva** [comment]
By no means am I a professional but I did try my best to come with a logo that combines "code health" and "graphing".
This logo is 100% original (made using canva designing tool)
I can change the title of the logo and also the basic design if you could suggest me regarding the changes and also upscale the logo


![graphing tool logo design template](https://user-images.githubusercontent.com/121221252/212925625-fc7546bd-15d8-42c7-85ea-623d87e77b2a.png)

**Comment by larrydiamond** [comment]
I love it!   That's great work!
A few quick changes - the name of the app is "Code Quality Graphing Tool" - can you put Code Quality in one line and Graphing Tool underneath it?
Also, colors..... black and white doesn't quite work, can you do some sort of <really anything> like what I was playing around with below?   
Again, I have no idea what I actually want and you're much better than me at this - I'm sure I'll love whatever you do!
Thank you very much - you're about to become the first person other than me to contribute to this project - welcome to the team!
![CQGT](https://user-images.githubusercontent.com/1066589/213030483-bad3be78-cead-4b40-bf73-681e0a2498ab.jpg)

**Comment by the-amazing-atharva** [comment]
Hey,
Thanks for the kind welcome.

I made 3 logos more, all customizable depending on your input.

**Logo 1 :**
![cqgt1Logo](https://user-images.githubusercontent.com/121221252/213069625-4d111c04-d512-457a-8ed4-a8b829c15667.png)
**Logo 2 :** (removed the laptop)
![cqgt2Logo](https://user-images.githubusercontent.com/121221252/213069637-2f268175-5d7b-4740-bfbf-113fae493e9d.png)
**Logo 3 :**
![cqgt3Logo](https://user-images.githubusercontent.com/121221252/213069643-589e9ee8-6a93-43f6-90e9-6352c6f18b8b.png)

Would like to hear your feedback to improve it further, or if you liked any of these I would like to send a PR !!!

**Comment by larrydiamond** [comment]
The second one is the winner - I love it, just please make the last bar the highest bar.   The height doesn't always need to be increasing, but the tool looks a whole lot better if the last bar is the highest bar and not the lowest bar :)

Thank you for doing this, I'm working on the web site now and you will be listed as a contributor once the logo is ready.   

Thank you very much for your contribution to Open Source!

**Comment by larrydiamond** [comment]
And btw you are a pleasure to work with, you've really been great!

**Comment by the-amazing-atharva** [comment]
Your Welcome !!!
Will make the necessary changes and post the logo again
Looking forward to seeing your site and thanks for considering me and adding me as a contributor ,

**Comment by the-amazing-atharva** [comment]
Updated logo :
Any more updates required ?
Also I am not that aware about contributions, should I be sending a PR?

![finalcqgtLogo-transformed](https://user-images.githubusercontent.com/121221252/213085839-fcdace81-5b70-43b6-9f45-fd1fe3e21e9b.png)

**Comment by larrydiamond** [comment]
That is perfect!   Great work!
Please send a pull request in a new branch with your files for the logo in the docs\images directory.   

Thank you very much!    

Besides announcing in Twitter and thanking you there, is there anyplace you'd like me to thank you to publicize your contribution?  Linkedin?

**Comment by the-amazing-atharva** [comment]
Your welcome!

Just sent a pull request with the file.

Nah, just twitter is enough 👍 

Thanks for being a good collaborator and helping me as a beginner

**Comment by larrydiamond** [comment]
https://twitter.com/LarryDiamondNY/status/1616208979058921472

Thank you and Congratulations to Atharva Salitri 
[@atharvas_twt](https://twitter.com/atharvas_twt)
 who made the first contribution to my open source project [http://CodeQualityGraph.com](https://t.co/0HZKHnHkwC) by creating the logo for the project - you've been a pleasure to work with and I thank you for your high quality work!
